<a href="https://colab.research.google.com/github/huojiajin/NLP-Assignments/blob/main/Week6_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print(tf.__version__)

import numpy as np

import pandas as pd
pd.set_option('precision', 8)

2.9.2


**Problem#1**

In [ ]:
# Init a result array
result = []

# Input Data
inputData = tf.constant([[0.1, 0.2]])

# Layer 1
w1 = tf.constant([[0.15], [0.05]])
b1 = 0.33
z1 = tf.matmul(inputData, w1) + b1
print("z1 : ", z1)

# Define a method to calculate the result of Layer 2
def calculate_layer2(a1):
  w2 = tf.constant([0.36])
  b2 = 0.56
  z2 = a1 * w2 + b2;
  print("z2 : ", z2)
  return a1 * w2 + b2

# Sigmoid
a1 = tf.sigmoid(tf.cast(z1, tf.float32))
z2 = calculate_layer2(a1)
a2 = tf.sigmoid(tf.cast(z2, tf.float32))
result.append(["Sigmiod", np.round(a1.numpy(), 3)[0][0], np.round(a2.numpy(), 3)[0][0]])

# Linear
a1 = z1
z2 = calculate_layer2(a1)
a2 = z2
result.append(["Linear", np.round(a1.numpy(), 3)[0][0], np.round(a2.numpy(), 3)[0][0]])

# Tanh
a1 = tf.tanh(z1)
z2 = calculate_layer2(a1)
a2 = tf.tanh(z2)
result.append(["Tanh", np.round(a1.numpy(), 3)[0][0], np.round(a2.numpy(), 3)[0][0]])

# ReLu
a1 = tf.nn.relu(z1)
z2 = calculate_layer2(a1)
a2 = tf.nn.relu(z2)
result.append(["ReLu", np.round(a1.numpy(), 3)[0][0], np.round(a2.numpy(), 3)[0][0]])

df = pd.DataFrame(result, columns = ["Activation Function", "a1", "a2"])
df

z1 :  tf.Tensor([[0.35500002]], shape=(1, 1), dtype=float32)
z2 :  tf.Tensor([[0.7716186]], shape=(1, 1), dtype=float32)
z2 :  tf.Tensor([[0.68780005]], shape=(1, 1), dtype=float32)
z2 :  tf.Tensor([[0.68268883]], shape=(1, 1), dtype=float32)
z2 :  tf.Tensor([[0.68780005]], shape=(1, 1), dtype=float32)


Activation Function     a1     a2
0             Sigmiod  0.588  0.684
1              Linear  0.355  0.688
2                Tanh  0.341  0.593
3                ReLu  0.355  0.688

**Problem#2**

In [ ]:
# Calculate the Gradient of Sigmoid
# with x = -4.0

print("Gradient of Sigmoid:")
x = -4.0
result = tf.sigmoid(x) * (1- tf.sigmoid(x))
print("x = -4.0, Gradient = ", np.round(result.numpy(), 4))

x = 0.5
result = tf.sigmoid(x) * (1- tf.sigmoid(x))
print("x = -0.5, Gradient = ", np.round(result.numpy(), 4))

x = 4.0
result = tf.sigmoid(x) * (1- tf.sigmoid(x))
print("x = 4.0, Gradient = ", np.round(result.numpy(), 4))

Gradient of Sigmoid:
x = -4.0, Gradient =  0.0177
x = -0.5, Gradient =  0.235
x = 4.0, Gradient =  0.0177


In [ ]:
# Calculate the Gradient of Tanh
# with x = -4.0

print("Gradient of Tanh:")
x = -4.0
result = 1 - (tf.tanh(x))**2
print("x = -4.0, Gradient = ", np.round(result.numpy(), 4))

x = 0.5
result = 1 - (tf.tanh(x))**2
print("x = -0.5, Gradient = ", np.round(result.numpy(), 4))

x = 4.0
result = 1 - (tf.tanh(x))**2
print("x = 4.0, Gradient = ", np.round(result.numpy(), 4))

Gradient of Tanh:
x = -4.0, Gradient =  0.0013
x = -0.5, Gradient =  0.7864
x = 4.0, Gradient =  0.0013


In [ ]:
# Calculate the Gradient of ReLu
# with x = -4.0

def calculate_gradient_ReLu(x):
  if(x <= 0):
    return 0
  else:
    return 1;

print("Gradient of ReLu:")
x = -4.0
result = calculate_gradient_ReLu(x)
print("x = -4.0, Gradient = ", result)

x = 0.5
result = calculate_gradient_ReLu(x)
print("x = -0.5, Gradient = ", result)

x = 4.0
result = calculate_gradient_ReLu(x)
print("x = 4.0, Gradient = ", result)

Gradient of ReLu:
x = -4.0, Gradient =  0
x = -0.5, Gradient =  1
x = 4.0, Gradient =  1


**Problem#3**

In [ ]:
# Compute the output of input wiht V1
v1 = [2.3, 1.2, 0.3, 0.0]
input = tf.constant(v1)
output = tf.nn.softmax(input)
print("Output of input with V1:")
print(output)

# Compute the output of input wiht V2
v1 = [1.9, 1.7, 2.6, 0.2, 1.3]
input = tf.constant(v1)
output = tf.nn.softmax(input)
print("Output of input with V2:")
print(output)


Output of input with V1:
tf.Tensor([0.6375659  0.21222727 0.08628516 0.06392162], shape=(4,), dtype=float32)
Output of input with V2:
tf.Tensor([0.21910708 0.17938972 0.44122744 0.04002725 0.12024851], shape=(5,), dtype=float32)


**Problem#4**

In [ ]:
# Define the method to compute cost function
def cost_function(target, computed_value):
  result = - (target * tf.math.log(computed_value) + (1 - target) * tf.math.log(1 - computed_value))
  return tf.cast(result, tf.float64).numpy()

target = 0
print("Target = ", target)
computed_value = 0.95
print("Computed Value = ", computed_value, ", Cost Function = ", cost_function(target, computed_value))

computed_value = 0.8
print("Computed Value = ", computed_value, ", Cost Function = ", cost_function(target, computed_value))

computed_value = 0.6
print("Computed Value = ", computed_value, ", Cost Function = ", cost_function(target, computed_value))

computed_value = 0.4
print("Computed Value = ", computed_value, ", Cost Function = ", cost_function(target, computed_value))

computed_value = 0.1
print("Computed Value = ", computed_value, ", Cost Function = ", cost_function(target, computed_value))

target = 1
print("Target = ", target)
computed_value = 0.95
print("Computed Value = ", computed_value, ", Cost Function = ", cost_function(target, computed_value))

computed_value = 0.8
print("Computed Value = ", computed_value, ", Cost Function = ", cost_function(target, computed_value))

computed_value = 0.6
print("Computed Value = ", computed_value, ", Cost Function = ", cost_function(target, computed_value))

computed_value = 0.4
print("Computed Value = ", computed_value, ", Cost Function = ", cost_function(target, computed_value))

computed_value = 0.1
print("Computed Value = ", computed_value, ", Cost Function = ", cost_function(target, computed_value))

Target =  0
Computed Value =  0.95 , Cost Function =  2.995732307434082
Computed Value =  0.8 , Cost Function =  1.6094379425048828
Computed Value =  0.6 , Cost Function =  0.9162907004356384
Computed Value =  0.4 , Cost Function =  0.5108255743980408
Computed Value =  0.1 , Cost Function =  0.10536054521799088
Target =  1
Computed Value =  0.95 , Cost Function =  0.051293306052684784
Computed Value =  0.8 , Cost Function =  0.2231435328722
Computed Value =  0.6 , Cost Function =  0.5108255743980408
Computed Value =  0.4 , Cost Function =  0.9162907004356384
Computed Value =  0.1 , Cost Function =  2.3025851249694824


**Problem#5**

In [ ]:
a = [[5, 2, 3], [26, 52, 92], [3, 0, 26]]

a1 = tf.argmax(a, axis = 0)
a2 = tf.argmax(a, axis = 1)

print("a1 = ", a1.numpy())
print("a2 = ", a2.numpy())

a1 =  [1 1 1]
a2 =  [0 2 2]


Problem#6

In [ ]:
# Define the method to compute
def compute(inputData, batchSize):
  if(inputData.shape[0] % batchSize != 0):
    raise Exception("batchSize is invalid!")

  result = []
  start_index = 0
  end_index = start_index + batchSize
  while(end_index <= inputData.shape[0]):
    # Slice the input
    input = inputData[start_index : end_index]
    #print("start_index : ", start_index, " end_index : ", end_index, " input:\n", input)
    start_index += batchSize
    end_index += batchSize
    # Compute the Layer1
    w1 = tf.constant([[-4, -6, -5], [3, 6, 4]])
    b1 = tf.constant([[-2, 3, -2]])
    outputH1 = tf.matmul(input, w1) + b1
    outputH1_Activation = tf.sigmoid(tf.cast(outputH1, tf.float64))

    # Compute the Layer2
    w2 = tf.cast(tf.constant([[5], [-9], [7]]), tf.float64)
    b2 = tf.cast(tf.constant([[4]]), tf.float64)
    outputH2 = tf.matmul(outputH1_Activation, w2) + b2
    outputH2_Activation = tf.sigmoid(tf.cast(outputH2, tf.float64))
    for a in outputH2_Activation.numpy():
      result.append(a[0])
    
  return result;

# Compute the input
inputData = [[0, 0], [1, 0], [0, 1], [1, 1]]
batchSize = 2
computed_Output = compute(tf.constant(inputData), batchSize)
#print(computed_Output)

# Convert the result to pandas
df = pd.DataFrame(inputData, columns = ["Input 1", "Input 2"])
ture_Output = [0, 1, 1, 0]
df["True Output"] = ture_Output

df["Computed output"] = computed_Output

# Compute the Error

error = (np.array(ture_Output) - np.array(computed_Output)) ** 2
df["Error"] = error

df

Input 1  Input 2  True Output  Computed output       Error
0        0        0            0       0.04137861  0.00171219
1        1        0            1       0.97319269  0.00071863
2        0        1            1       0.99201349  0.00006378
3        1        1            0       0.01791470  0.00032094